In [1]:
import numpy as np

a = [1,2,3,4,5]
b = np.array(a)

print(type(a))
print(a)
print('--------')
print(type(b))
print(b)


<class 'list'>
[1, 2, 3, 4, 5]
--------
<class 'numpy.ndarray'>
[1 2 3 4 5]


In [4]:
print(a[0])
print(b[0])
print(a[0:3])
print(b[0:3])


1
1
[1, 2, 3]
[1 2 3]


In [5]:
print(a+b)
print(b+b)


[ 2  4  6  8 10]
[ 2  4  6  8 10]


In [9]:
print(b)
print(b/2)
print(b//2)
print(b+2)

[1 2 3 4 5]
[0.5 1.  1.5 2.  2.5]
[0 1 1 2 2]
[3 4 5 6 7]


In [10]:
import pandas as pd
a = pd.Series([1,2,3,4,5])
print(a)
print(type(a))

0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.core.series.Series'>


In [11]:
a = pd.Series([1,2,3,4], index=['a','b','c','d'])
print(a)

a    1
b    2
c    3
d    4
dtype: int64


In [12]:
a = pd.Series({'a' : 1, 'b' : 2 , 'c' : 3})
print(a)

a    1
b    2
c    3
dtype: int64


In [20]:
a = pd.Series({'a' : [1,1,1], 'b' : [2,2,2], 'c' : [3,3,3]})
b = pd.DataFrame({'a' : [1,1,1], 'b' : [2,2,2], 'c' : [3,3,3]})
print(a)
print(type(a))
print(b)
print(type(b))


a    [1, 1, 1]
b    [2, 2, 2]
c    [3, 3, 3]
dtype: object
<class 'pandas.core.series.Series'>
   a  b  c
0  1  2  3
1  1  2  3
2  1  2  3
<class 'pandas.core.frame.DataFrame'>


In [21]:
b['b'] = [3,4,5]
print(b)

   a  b  c
0  1  3  3
1  1  4  3
2  1  5  3


In [23]:
b.index = ['x', 'y', 'z']
b.columns = ['i', 'j', 'k']
print(b)

   i  j  k
x  1  3  3
y  1  4  3
z  1  5  3


In [24]:
print(b.describe())

         i    j    k
count  3.0  3.0  3.0
mean   1.0  4.0  3.0
std    0.0  1.0  0.0
min    1.0  3.0  3.0
25%    1.0  3.5  3.0
50%    1.0  4.0  3.0
75%    1.0  4.5  3.0
max    1.0  5.0  3.0


In [25]:
# sum()
print(b.sum())

i     3
j    12
k     9
dtype: int64


In [26]:
print(b.sum(axis=1))

x    7
y    8
z    9
dtype: int64


In [27]:
data = pd.read_csv('ml-latest-small/movies.csv')
data

movieId                                      title  \
0           1                           Toy Story (1995)   
1           2                             Jumanji (1995)   
2           3                    Grumpier Old Men (1995)   
3           4                   Waiting to Exhale (1995)   
4           5         Father of the Bride Part II (1995)   
...       ...                                        ...   
9737   193581  Black Butler: Book of the Atlantic (2017)   
9738   193583               No Game No Life: Zero (2017)   
9739   193585                               Flint (2017)   
9740   193587        Bungo Stray Dogs: Dead Apple (2018)   
9741   193609        Andrew Dice Clay: Dice Rules (1991)   

                                           genres  
0     Adventure|Animation|Children|Comedy|Fantasy  
1                      Adventure|Children|Fantasy  
2                                  Comedy|Romance  
3                            Comedy|Drama|Romance  
4                                          Comedy  
...                                           ...  
9737              Action|Animation|Comedy|Fantasy  
9738                     Animation|Comedy|Fantasy  
9739                                        Drama  
9740                             Action|Animation  
9741                                       Comedy  

[9742 rows x 3 columns]

In [28]:
genre = []

for i in data['genres'] :
    genre.extend(i.split('|'))
print(len(genre))

22084


In [29]:
uq_genre = pd.unique(genre)
print(uq_genre)
print(len(uq_genre))

['Adventure' 'Animation' 'Children' 'Comedy' 'Fantasy' 'Romance' 'Drama'
 'Action' 'Crime' 'Thriller' 'Horror' 'Mystery' 'Sci-Fi' 'War' 'Musical'
 'Documentary' 'IMAX' 'Western' 'Film-Noir' '(no genres listed)']
20


In [31]:
zero_data = np.zeros(len(uq_genre))
result = pd.DataFrame(zero_data, index=uq_genre, columns=['count'])
print(result)

                    count
Adventure             0.0
Animation             0.0
Children              0.0
Comedy                0.0
Fantasy               0.0
Romance               0.0
Drama                 0.0
Action                0.0
Crime                 0.0
Thriller              0.0
Horror                0.0
Mystery               0.0
Sci-Fi                0.0
War                   0.0
Musical               0.0
Documentary           0.0
IMAX                  0.0
Western               0.0
Film-Noir             0.0
(no genres listed)    0.0


In [32]:
for i in genre :
    result.loc[i] += 1

print(result)

                     count
Adventure           1263.0
Animation            611.0
Children             664.0
Comedy              3756.0
Fantasy              779.0
Romance             1596.0
Drama               4361.0
Action              1828.0
Crime               1199.0
Thriller            1894.0
Horror               978.0
Mystery              573.0
Sci-Fi               980.0
War                  382.0
Musical              334.0
Documentary          440.0
IMAX                 158.0
Western              167.0
Film-Noir             87.0
(no genres listed)    34.0
